---
logger:
  default: winston
  providers:
    -
      name: winston
      type: '~/lib'
  winston:
    level: error
    format: json
    transports:
      files:
        - 
          filename: out.log