---
logger:
  default: winston
  providers:
    -
      name: winston
      type: '~/lib'
      factories:
        files: '~/lib/factories/files'
        console: '~/lib/factories/console'
      level: debug
      transports:
        files:
          - 
            filename: out.log
        console: true